/* Generated By:JavaCC: Do not edit this line. MAliceConstants.java */
package parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface MAliceConstants {

   /** End of File. */
   int EOF = 0;
   /** RegularExpression Id. */
   int COMMENT = 5;
   /** RegularExpression Id. */
   int COMMA = 6;
   /** RegularExpression Id. */
   int DOT = 7;
   /** RegularExpression Id. */
   int AND = 8;
   /** RegularExpression Id. */
   int BUT = 9;
   /** RegularExpression Id. */
   int THEN = 10;
   /** RegularExpression Id. */
   int WASA = 11;
   /** RegularExpression Id. */
   int BECAME = 12;
   /** RegularExpression Id. */
   int T_NUMBER = 13;
   /** RegularExpression Id. */
   int T_LETTER = 14;
   /** RegularExpression Id. */
   int T_STRING = 15;
   /** RegularExpression Id. */
   int SPOKE = 16;
   /** RegularExpression Id. */
   int WHATWAS = 17;
   /** RegularExpression Id. */
   int HAD = 18;
   /** RegularExpression Id. */
   int SPIDER = 19;
   /** RegularExpression Id. */
   int QMARK = 20;
   /** RegularExpression Id. */
   int SAID = 21;
   /** RegularExpression Id. */
   int ARRINDEX = 22;
   /** RegularExpression Id. */
   int PIECE = 23;
   /** RegularExpression Id. */
   int LEFTBRACKET = 24;
   /** RegularExpression Id. */
   int RIGHTBRACKET = 25;
   /** RegularExpression Id. */
   int EXCL = 26;
   /** RegularExpression Id. */
   int RETURN = 27;
   /** RegularExpression Id. */
   int THEROOM = 28;
   /** RegularExpression Id. */
   int CONTAINEDA = 29;
   /** RegularExpression Id. */
   int THELOOKINGGLASS = 30;
   /** RegularExpression Id. */
   int CHANGEDA = 31;
   /** RegularExpression Id. */
   int WENTTHROUGH = 32;
   /** RegularExpression Id. */
   int EVENTUALLY = 33;
   /** RegularExpression Id. */
   int BECAUSE = 34;
   /** RegularExpression Id. */
   int ENOUGH = 35;
   /** RegularExpression Id. */
   int EITHER = 36;
   /** RegularExpression Id. */
   int PERHAPS = 37;
   /** RegularExpression Id. */
   int SO = 38;
   /** RegularExpression Id. */
   int OR = 39;
   /** RegularExpression Id. */
   int MAYBE = 40;
   /** RegularExpression Id. */
   int UNSURE = 41;
   /** RegularExpression Id. */
   int WHICH = 42;
   /** RegularExpression Id. */
   int BIT_COMP = 43;
   /** RegularExpression Id. */
   int DRANK = 44;
   /** RegularExpression Id. */
   int ATE = 45;
   /** RegularExpression Id. */
   int BOOL_AND = 46;
   /** RegularExpression Id. */
   int BOOL_OR = 47;
   /** RegularExpression Id. */
   int PLUS = 48;
   /** RegularExpression Id. */
   int MINUS = 49;
   /** RegularExpression Id. */
   int MULT = 50;
   /** RegularExpression Id. */
   int DIV = 51;
   /** RegularExpression Id. */
   int MOD = 52;
   /** RegularExpression Id. */
   int BIT_AND = 53;
   /** RegularExpression Id. */
   int BIT_XOR = 54;
   /** RegularExpression Id. */
   int BIT_OR = 55;
   /** RegularExpression Id. */
   int BOOL_GT = 56;
   /** RegularExpression Id. */
   int BOOL_GTE = 57;
   /** RegularExpression Id. */
   int BOOL_LT = 58;
   /** RegularExpression Id. */
   int BOOL_LTE = 59;
   /** RegularExpression Id. */
   int BOOL_EQ = 60;
   /** RegularExpression Id. */
   int BOOL_NOTEQ = 61;
   /** RegularExpression Id. */
   int INT = 62;
   /** RegularExpression Id. */
   int IDENTIFIER = 63;
   /** RegularExpression Id. */
   int CHAR = 64;
   /** RegularExpression Id. */
   int DIGIT = 65;
   /** RegularExpression Id. */
   int LITERALCHAR = 66;
   /** RegularExpression Id. */
   int STRING_LITERAL = 67;

   /** Lexical state. */
   int DEFAULT = 0;

   /** Literal token values. */
   String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"",
         "<COMMENT>", "\",\"", "\".\"", "\"and\"", "\"but\"", "\"then\"",
         "\"was a\"", "\"became\"", "\"number\"", "\"letter\"", "\"string\"",
         "\"spoke\"", "\"what was\"", "\"had\"", "\"spider\"", "\"?\"",
         "\"said Alice\"", "\"\\\'s\"", "\"piece\"", "\"(\"", "\")\"", "\"!\"",
         "\"Alice found\"", "\"The room\"", "\"contained a\"",
         "\"The Looking-Glass\"", "\"changed a\"", "\"went through\"",
         "\"eventually\"", "\"because\"", "\"enough times\"", "\"either\"",
         "\"perhaps\"", "\"so\"", "\"or\"", "\"maybe\"",
         "\"Alice was unsure\"", "\"which\"", "\"~\"", "\"drank\"", "\"ate\"",
         "\"&&\"", "\"||\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"%\"",
         "\"&\"", "\"^\"", "\"|\"", "\">\"", "\">=\"", "\"<\"", "\"<=\"",
         "\"==\"", "\"!=\"", "<INT>", "<IDENTIFIER>", "<CHAR>", "<DIGIT>",
         "<LITERALCHAR>", "<STRING_LITERAL>", };

}
